type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/atim/bottom/repo/fedora-%OS_VERSION%/atim-bottom-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/frostyx/qtile/repo/fedora-%OS_VERSION%/frostyx-qtile-fedora-%OS_VERSION%.repo

install:
  - python-pywayland
  - python-pywlroots
  - qtile
