type: rpm-ostree
install:
  - dcoreutilsd
  - dcliphistd
  - dcmaked
  - dcurld
  - dfuzzeld
  - drsyncd
  - dwgetd
  - dripgrepd
  - dgojqd
  - dnpmd
  - dmesond
  - dtypescriptd
  - dgjsd
  - ddart-sassd
  - daxel
  - dtinyxml2d
  - dgtkmm3d
  - dgtksourceviewmmd
  - dcairomm
  - dpython-buildd
  - dpython-material-color-utilitiesd
  - dpython-pillowd
  - dpython-poetryd
  - dpython-pywald
  - dpython-setuptools-scmd
  - dpython-wheel
  - dhyprland-gitd
  - dxorg-xrandr
  - dpavucontrold
  - dwireplumberd
  - dlibdbusmenu-gtk3d
  - dplasma-browser-integrationd
  - dplayerctld
  - dswww
  - dwebp-pixbuf-loaderd
  - dgtk-layer-shelld
  - dgtk3d
  - dgtksourceview3d
  - dgobject-introspectiond
  - dupowerd
  - dyadd
  - dydotool
  - dpolkit-gnomed
  - dgnome-keyringd
  - dgnome-control-centerd
  - dblueberryd
  - dnetworkmanagerd
  - dbrightnessctld
  - dwlsunsetd
  - dgnome-bluetooth-3.0
  - dpython-pywaylandd
  - dpython-psutild
  - dhypridle-gitd
  - dhyprlock-gitd
  - dwlogoutd
  - dwl-clipboardd
  - dhyprpicker-gitd
  - danyrun-git
  - dadw-gtk3-gitd
  - dqt5ctd
  - dqt5-waylandd
  - dgradience-gitd
  - dfontconfigd
  - dlexend-fonts-gitd
  - dttf-jetbrains-mono-nerdd
  - dttf-material-symbols-variable-gitd
  - dttf-space-mono-nerdd
  - dfishd
  - dfootd
  - dstarship
  - dswappyd
  - dwf-recorderd
  - dgrimd
  - dtesseractd
  - dtesseract-data-engd
  - dslurp