type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/atim/bottom/repo/fedora-%OS_VERSION%/atim-bottom-fedora-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-%OS_VERSION%.repo
  - https://copr.fedorainfracloud.org/coprs/lyessaadi/gradience/repo/fedora-%OS_VERSION%/lyessaadi-gradience-%OS_VERSION%.repo

install:
  - coreutils
  - cliphist
  - cmake
  - curl
  - fuzzel
  - rsync
  - wget
  - ripgrep
  - gojq
  - npm
  - meson
  - typescript
  - gjs
  # - dart-sass
  - axel
  - tinyxml2
  - gtk3
  - gtksourceview3
  - cairomm
  - python-build
  # - python-material-color-utilities
  - python-pillow
  - python-poetry
  # - python-pywal
  # - python-setuptools-scm
  - python-wheel
  - xrandr
  - pavucontrol
  - wireplumber
  - libdbusmenu-gtk3
  - plasma-browser-integration
  - playerctl
  - swww
  - webp-pixbuf-loader
  - gtk-layer-shell
  - gtk3
  - gtksourceview3
  - gobject-introspection
  - upower
  - yad
  - ydotool
  - polkit-gnome
  - gnome-keyring
  - gnome-control-center
  # - blueberry
  - bluez
  - brightnessctl
  - wlsunset
  # - gnome-bluetooth-3.0
  - python-pywayland
  - python-psutil
  - hypridle
  - hyprlock
  - wlogout
  - wl-clipboard
  - hyprpicker
  # - anyrun
  - adw-gtk3-theme
  - qt5ct
  - qt5-qtwayland
  - gradience
  - fontconfig
  # - lexend-fonts
  # - jetbrains-mono-nerd
  - material-icons-fonts
  # - ttf-space-mono-nerd
  - fish
  - foot
  - starship
  - swappy
  - wf-recorder
  - grim
  - tesseract
  - slurp